# Generated by Django 5.1.3 on 2025-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type_needed',
            field=models.CharField(choices=[('DEA 1.1+', 'DEA 1.1 Positive'), ('DEA 1.1-', 'DEA 1.1 Negative'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('DEA 1.1+', 'DEA 1.1 Positive'), ('DEA 1.1-', 'DEA 1.1 Negative'), ('DEA 1.2', 'DEA 1.2'), ('DEA 3', 'DEA 3'), ('DEA 4', 'DEA 4'), ('DEA 5', 'DEA 5'), ('DEA 7', 'DEA 7')], max_length=10),
        ),
    ]
