# Generated by Django 5.1.3 on 2025-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_bloodrequest_blood_type_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
