# Generated by Django 5.1.3 on 2025-07-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='health_certificate',
            field=models.FileField(default=0, upload_to='health_certificates/'),
            preserve_default=False,
        ),
    ]
