# Generated by Django 5.1.3 on 2025-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_bloodrequest_is_fulfilled_bloodrequest_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
