# Generated by Django 5.1.3 on 2025-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_alter_bloodrequest_urgency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
