# Generated by Django 5.1.3 on 2025-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('found_location', models.CharField(max_length=255)),
                ('date_found', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_dogs/')),
            ],
        ),
    ]
