# Generated by Django 5.1.3 on 2025-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_founddog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founddog',
            options={'ordering': ['-date_found']},
        ),
        migrations.AlterModelOptions(
            name='lostdog',
            options={'ordering': ['-date_lost']},
        ),
        migrations.RenameField(
            model_name='lostdog',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='founddog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founddog',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='lostdog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostdog',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lostdog',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
