# Generated by Django 5.2.4 on 2025-07-23 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_alter_founddog_options_alter_lostdog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founddog',
            options={'ordering': ['-date_found'], 'verbose_name': 'Found Dog', 'verbose_name_plural': 'Found Dogs'},
        ),
        migrations.AlterModelOptions(
            name='lostdog',
            options={'ordering': ['-date_lost'], 'verbose_name': 'Lost Dog', 'verbose_name_plural': 'Lost Dogs'},
        ),
        migrations.AddField(
            model_name='founddog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founddog',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founddog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lostdog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostdog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='founddog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='founddog',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lostdog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lostdog',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
