# Generated by Django 5.1.3 on 2025-07-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0004_alter_founddog_options_alter_lostdog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founddog',
            name='age',
        ),
    ]
