# Generated by Django 5.2.4 on 2025-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0005_remove_founddog_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddog',
            name='image',
            field=models.ImageField(default=0, upload_to='found_dogs/'),
            preserve_default=False,
        ),
    ]
