# Generated by Django 5.1.3 on 2025-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0006_alter_founddog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddog',
            name='breed',
            field=models.CharField(blank=True, choices=[('beagle', 'Beagle'), ('border_collie', 'Border Collie'), ('boxer', 'Boxer'), ('bulldog', 'Bulldog'), ('chihuahua', 'Chihuahua'), ('cocker_spaniel', 'Cocker Spaniel'), ('dalmatian', 'Dalmatian'), ('dachshund', 'Dachshund'), ('doberman', 'Doberman Pinscher'), ('germanshepherd', 'German Shepherd'), ('golden', 'Golden Retriever'), ('great_dane', 'Great Dane'), ('husky', 'Siberian Husky'), ('labrador', 'Labrador Retriever'), ('pom', 'Pomeranian'), ('poodle', 'Poodle'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('shih_tzu', 'Shih Tzu'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lostdog',
            name='breed',
            field=models.CharField(choices=[('beagle', 'Beagle'), ('border_collie', 'Border Collie'), ('boxer', 'Boxer'), ('bulldog', 'Bulldog'), ('chihuahua', 'Chihuahua'), ('cocker_spaniel', 'Cocker Spaniel'), ('dalmatian', 'Dalmatian'), ('dachshund', 'Dachshund'), ('doberman', 'Doberman Pinscher'), ('germanshepherd', 'German Shepherd'), ('golden', 'Golden Retriever'), ('great_dane', 'Great Dane'), ('husky', 'Siberian Husky'), ('labrador', 'Labrador Retriever'), ('pom', 'Pomeranian'), ('poodle', 'Poodle'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('shih_tzu', 'Shih Tzu'), ('other', 'Other')], max_length=100),
        ),
    ]
