# Generated by Django 5.1.3 on 2025-07-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0008_founddog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founddog',
            name='reporter_name',
        ),
    ]
