# Generated by Django 5.2.4 on 2025-08-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0010_alter_founddog_breed_alter_lostdog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='founddog',
            name='found_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='founddog',
            name='found_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
