# Generated by Django 5.1.3 on 2025-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='contact_info',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='health_certificate',
            field=models.FileField(default=9, upload_to='dog_certificates/'),
            preserve_default=False,
        ),
    ]
