# Generated by Django 5.1.3 on 2025-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_dog_contact_info_dog_health_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='sterilized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='temperament',
            field=models.TextField(default='very friendly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
