# Generated by Django 5.1.3 on 2025-07-16 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_dog_gender_dog_medical_notes_dog_sterilized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_dogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
