# Generated by Django 5.2.4 on 2025-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_dog_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('labrador', 'Labrador Retriever'), ('golden', 'Golden Retriever'), ('beagle', 'Beagle'), ('germanshepherd', 'German Shepherd'), ('bulldog', 'Bulldog'), ('poodle', 'Poodle'), ('chihuahua', 'Chihuahua'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('husky', 'Siberian Husky'), ('boxer', 'Boxer'), ('dachshund', 'Dachshund'), ('doberman', 'Doberman Pinscher'), ('shih_tzu', 'Shih Tzu'), ('great_dane', 'Great Dane'), ('dalmatian', 'Dalmatian'), ('cocker_spaniel', 'Cocker Spaniel'), ('border_collie', 'Border Collie'), ('pom', 'Pomeranian'), ('other', 'Other')], max_length=100),
        ),
    ]
