# Generated by Django 5.2.4 on 2025-07-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('beagle', 'Beagle'), ('border_collie', 'Border Collie'), ('boxer', 'Boxer'), ('bulldog', 'Bulldog'), ('chihuahua', 'Chihuahua'), ('cocker_spaniel', 'Cocker Spaniel'), ('dalmatian', 'Dalmatian'), ('dachshund', 'Dachshund'), ('doberman', 'Doberman Pinscher'), ('germanshepherd', 'German Shepherd'), ('golden', 'Golden Retriever'), ('great_dane', 'Great Dane'), ('husky', 'Siberian Husky'), ('labrador', 'Labrador Retriever'), ('pom', 'Pomeranian'), ('poodle', 'Poodle'), ('pug', 'Pug'), ('rottweiler', 'Rottweiler'), ('shih_tzu', 'Shih Tzu'), ('other', 'Other')], max_length=100),
        ),
    ]
