# Generated by Django 5.2.4 on 2025-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('Beagle', 'Beagle'), ('Border Collie', 'Border Collie'), ('Boxer', 'Boxer'), ('Bulldog', 'Bulldog'), ('Chihuahua', 'Chihuahua'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Dalmatian', 'Dalmatian'), ('Dachshund', 'Dachshund'), ('Doberman Pinscher', 'Doberman Pinscher'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Great Dane', 'Great Dane'), ('Labrador Retriever', 'Labrador Retriever'), ('Pomeranian', 'Pomeranian'), ('Poodle', 'Poodle'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Siberian Husky', 'Siberian Husky'), ('Shih Tzu', 'Shih Tzu'), ('Other', 'Other')], max_length=100),
        ),
    ]
