name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST https://api.render.com/v1/services/srv-d2k7s4e3jp1c73fucq0g/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"